### ISSUE TITLE
error in PSSharedGoods.psd1 RequiredModules wrong version PSWriteColor

### ISSUE THREAD

**Issue by uwefranke** [EvotecIT/PSSharedGoods#11]
error in PSSharedGoods.psd1

RequiredModules      = @(@{ModuleName = 'PSWriteColor'; GUID = '0b0ba5c5-ec85-4c2b-a718-874e55a8bc3f'; ModuleVersion = '**0.87**'; }, 
        @{ModuleName = 'Connectimo'; GUID = 'e4f4f8a6-473e-4ba5-8166-480658c11421'; ModuleVersion = '0.0.5'; })

RequiredModules      = @(@{ModuleName = 'PSWriteColor'; GUID = '0b0ba5c5-ec85-4c2b-a718-874e55a8bc3f'; ModuleVersion = '**0.87.0**'; }, 
        @{ModuleName = 'Connectimo'; GUID = 'e4f4f8a6-473e-4ba5-8166-480658c11421'; ModuleVersion = '0.0.5'; })

**Comment by PrzemyslawKlys** [comment]
Can you elaborate where you have an issue? what error you're getting? The pswritecolor version is 0.87 not 0.87.0

**Comment by uwefranke** [comment]
Hi,
If i install from powershellgallery Download is Version 0.87.0

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Przemysław Kłys <notifications@github.com>
Gesendet: Friday, June 19, 2020 11:21:54 AM
An: EvotecIT/PSSharedGoods <PSSharedGoods@noreply.github.com>
Cc: Uwe Franke <uwe.franke@outlook.com>; Author <author@noreply.github.com>
Betreff: Re: [EvotecIT/PSSharedGoods] error in PSSharedGoods.psd1 RequiredModules wrong version PSWriteColor (#11)


Can you elaborate where you have an issue? what error you're getting? The pswritecolor version is 0.87 not 0.87.0

**Comment by uwefranke** [comment]
Hi,

if i download manuell the file is pscolor.0.87.0.nupkg.
Install is C:\Program Files\WindowsPowerShell\Modules\PSWriteColor\0.87.0.
I think nuget need more the one point in version.
if i delete the null then it work.
C:\Program Files\WindowsPowerShell\Modules\PSWriteColor\0.87


Uwe

Mobil: +49 (0) 176 -??48 66??44 39
Mail: uwe.franke@outlook.com<mailto:uwe.franke@outlook.com>
www.scriptbb.com<http://www.scriptbb.com>

??

________________________________
Von: Przemysław Kłys <notifications@github.com>
Gesendet: Freitag, 19. Juni 2020 11:21
An: EvotecIT/PSSharedGoods <PSSharedGoods@noreply.github.com>
Cc: Uwe Franke <uwe.franke@outlook.com>; Author <author@noreply.github.com>
Betreff: Re: [EvotecIT/PSSharedGoods] error in PSSharedGoods.psd1 RequiredModules wrong version PSWriteColor (#11)


Can you elaborate where you have an issue? what error you're getting? The pswritecolor version is 0.87 not 0.87.0

**Comment by PrzemyslawKlys** [comment]
![image](https://user-images.githubusercontent.com/15063294/85120147-1ee2c900-b223-11ea-8735-6ec0ff147485.png)

It works here?

**Comment by uwefranke** [comment]
Hi,

yes that work, but not the manuell download off *.nupkg files.
This files i need for systems without internet.

 Uwe

Mobil: +49 (0) 176 -??48 66??44 39
Mail: uwe.franke@outlook.com<mailto:uwe.franke@outlook.com>
www.scriptbb.com<http://www.scriptbb.com>

??
________________________________
Von: Przemysław Kłys <notifications@github.com>
Gesendet: Freitag, 19. Juni 2020 11:51
An: EvotecIT/PSSharedGoods <PSSharedGoods@noreply.github.com>
Cc: Uwe Franke <uwe.franke@outlook.com>; Author <author@noreply.github.com>
Betreff: Re: [EvotecIT/PSSharedGoods] error in PSSharedGoods.psd1 RequiredModules wrong version PSWriteColor (#11)


[image]<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F15063294%2F85120147-1ee2c900-b223-11ea-8735-6ec0ff147485.png&data=02%7C01%7C%7Cfffa74f646854129578f08d814364de1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637281570747453838&sdata=QRihfozOWiY9KjpVeRzNxXht%2FB0l7mAVX5aE%2B6qvF6c%3D&reserved=0>

It works here?

**Comment by PrzemyslawKlys** [comment]
Have you tried using my method for portable modules? https://evotec.xyz/making-powershellgallery-modules-portable/

**Comment by uwefranke** [comment]
No

i use that:


Register-PSRepository "InstallModule" -SourceLocation "C:\PSMLokal"

install-module -Name pswriteword -Repository "InstallModule" -Force

the dir contains:
C:\PSMLokal\connectimo.0.0.5.nupkg
C:\PSMLokal\pssharedgoods.0.0.147.nupkg
C:\PSMLokal\pswritecolor.0.87.0.nupkg
C:\PSMLokal\pswriteword.1.1.8.nupkg



Uwe

Mobil: +49 (0) 176 -??48 66??44 39
Mail: uwe.franke@outlook.com<mailto:uwe.franke@outlook.com>
www.scriptbb.com<http://www.scriptbb.com>

??
________________________________
Von: Przemysław Kłys <notifications@github.com>
Gesendet: Freitag, 19. Juni 2020 12:02
An: EvotecIT/PSSharedGoods <PSSharedGoods@noreply.github.com>
Cc: Uwe Franke <uwe.franke@outlook.com>; Author <author@noreply.github.com>
Betreff: Re: [EvotecIT/PSSharedGoods] error in PSSharedGoods.psd1 RequiredModules wrong version PSWriteColor (#11)


Have you tried using my method for portable modules? https://evotec.xyz/making-powershellgallery-modules-portable/<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fevotec.xyz%2Fmaking-powershellgallery-modules-portable%2F&data=02%7C01%7C%7C98e7eaf9932a4242cd1108d81437dc22%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637281577425815702&sdata=2MYV7iBr4jjPj2W1ojyMW2B%2Bgf%2FvSQDN1S48LSFW1qU%3D&reserved=0>

**Comment by PrzemyslawKlys** [comment]
i understand but why not use Save-Module ? which will unpack it properly and you don't have to play with nugets? This is what my script uses.

**Comment by uwefranke** [comment]
that way i use for all offline modules is easy to chage a version off one file

nuget need 2 points:

https://devblogs.microsoft.com/devops/versioning-nuget-packages-cd-1/


Uwe

Mobil: +49 (0) 176 -??48 66??44 39
Mail: uwe.franke@outlook.com<mailto:uwe.franke@outlook.com>
www.scriptbb.com<http://www.scriptbb.com>

??
________________________________
Von: Przemysław Kłys <notifications@github.com>
Gesendet: Freitag, 19. Juni 2020 12:18
An: EvotecIT/PSSharedGoods <PSSharedGoods@noreply.github.com>
Cc: Uwe Franke <uwe.franke@outlook.com>; Author <author@noreply.github.com>
Betreff: Re: [EvotecIT/PSSharedGoods] error in PSSharedGoods.psd1 RequiredModules wrong version PSWriteColor (#11)


i understand but why not use Save-Module ? which will unpack it properly and you don't have to play with nugets? This is what my script uses.

**Comment by PrzemyslawKlys** [comment]
This would mean publishing new PSWriteColor. I'll think if I have something to add to PSwritecolor.

**Comment by PrzemyslawKlys** [comment]
Fixed in PSWriteColor 0.87.1, PSSharedGood 0.0.148.
