### ISSUE TITLE
No data from Get-PSService when querying remote server

### ISSUE THREAD

**Issue by adriandeller** [EvotecIT/PSSharedGoods#14]
found this issue when I run
`Invoke-Testimo -ReturnResults -Sources DCServices`

reference: https://github.com/EvotecIT/Testimo/blob/master/Private/SourcesDomainControllers/Services.ps1

> Warning "Get-CimData - No data for computer Computer. Most likely an error on receiving side."

Note: it still works when running the function using the "-All" switch parameter

**Comment by PrzemyslawKlys** [comment]
What do you get when running this? 

```
$DomainController = 'ad1.ad.evotec.xyz'
$Services = @('ADWS', 'DNS', 'DFS', 'DFSR', 'Eventlog', 'EventSystem', 'KDC', 'LanManWorkstation', 'LanManServer', 'NetLogon', 'NTDS', 'RPCSS', 'SAMSS', 'Spooler', 'W32Time', 'XblGameSave', 'XblAuthManager')
Get-PSService -Computers $DomainController -Services $Services | Format-Table
```

Of course change DomainController ?

**Comment by PrzemyslawKlys** [comment]
Ok, i think I know - it would seem the warning happens if there is no response from non-responding DC. Is that the case for you?

**Comment by adriandeller** [comment]
`Get-PSService -Computers $DomainController -Services $Services | Format-Table`

> WARNING: Get-CimData - No data for computer SERVER-FQDN Most likely an error on receiving side.


`Get-PSService -Computers $DomainController -All | Format-Table`

>
> Name                       Status ExitCode DesktopInteract ErrorControl PathName
> ADWS                       OK            0           False Normal       C:\windows\ADWS\Microsoft.ActiveDirectory.WebServices.exe
>

**Comment by PrzemyslawKlys** [comment]
i'll rework Get-CimData to return actual errors so you can see what's wrong.

**Comment by adriandeller** [comment]
It seems to me that Get-CimData can't handle properly the array provided with the parameter "Properties":
`$Information = Get-CimData -ComputerName $ComputerName -Protocol $Protocol -Class $Class -Properties $Properties`

If you just provide an asterix, like when using the parameter "All", it works.

**Comment by PrzemyslawKlys** [comment]
Which system do you work with? can you give me all properties that do work. Maybe it's related to version of the system I'm targeting?

**Comment by adriandeller** [comment]
target OS is Windows Server 2012 R2

CIM session itself works:
`$session = New-CimSession -ComputerName $DomainController`
`Get-CimInstance -ClassName Win32_service -CimSession $session`

and I found the problematic property, its "DelayedAutoStart" which is not available

**Comment by PrzemyslawKlys** [comment]
I'm now using * to query as it's not a big deal. I also improved error handling so should now be visible why it fails and where.

**Comment by PrzemyslawKlys** [comment]
Published new version

**Comment by adriandeller** [comment]
> Published new version

updates module, tested and issue is solved. many thanks!
