### ISSUE TITLE
Get-ComputerTask Actions empty

### ISSUE THREAD

**Issue by itpro-tips** [EvotecIT/PSSharedGoods#15]
Hi,

In [Get-ComputerTask.ps1](https://github.com/EvotecIT/PSSharedGoods/blob/master/Public/Computers/Get-ComputerTask.ps1) Actions is empty.
Indeed the Actions only exist in _Get-ScheduledTask_.

Test on Windows Server 2016.

**Comment by PrzemyslawKlys** [comment]
This should fix it. A small mistake on my part.

**Comment by itpro-tips** [comment]
Awesome, like always 😁
