### ISSUE TITLE
I don't understand what I am doing wrong

### ISSUE THREAD

**Issue by sysop200** [EvotecIT/PSSharedGoods#16]
The first time I open ISE I enter the get-module command, everything is clean, there are no extra modules. And if I enter the command Get-Module -ListAvailable, modules appear in the list immediately
Connectimo
PSSharedGoods
PSWriteColor
I don't understand what I did to make these modules load automatically

**Comment by PrzemyslawKlys** [comment]
Beginning in PowerShell 3.0, PowerShell imports modules automatically the first time that you run any command in an installed module. You can now use the commands in a module without any set-up or profile configuration, so there's no need to manage modules after you install them on your computer.

Please read: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_modules

Get-Module shows "currently" autoloader modules in your session. Get-Module -ListAvailable shows modules that are available for you to use if need arises. Once you use any cmdlet from any module it will automatically auto import itself and when you type Get-Module again it will show as in use.

**Comment by sysop200** [comment]
I didn't seem to want to use them.
Other modules are not loaded. How can I disable this behavior?

**Comment by PrzemyslawKlys** [comment]
What you wanted to use? Get-Module shows active modules. Get-Module -listavailable shows all installed modules. Those won't be  "running"until you use them. If you want to get rid of them you can uninstall them. Keep in mind that those 3 modules you mentioned are connected to PSSharedGoods.

**Comment by sysop200** [comment]
I work very closely with your modules, they are important in my work. Thank you so much for them.
But at the moment, I just loaded, created my new module and wanted to see if it is in the list or not, but I have not used these 3 modules at the current time. As a result, they loaded automatically

**Comment by PrzemyslawKlys** [comment]
If you use any cmdlet from PSSharedGoods - it will autoload PSWriteCOlor/COnnectimo for now. So that's most likely what you're seeing.

**Comment by PrzemyslawKlys** [comment]
So if you load any function from PSSharedGoods it autoloads those

![image](https://user-images.githubusercontent.com/15063294/105991612-501e5400-60a4-11eb-81ff-b00748ae7501.png)

**Comment by sysop200** [comment]
The fact of the matter is that I do not use modules and cmlet from
Connectimo
PSSharedGoods
PSWriteColor
Let's point by point what I did.
1.I changed the standard paths in the $ env: PSModulePath variable, adding the path to my new module, not related in any way to these 3.
2.I opened ISE and entered the get-module command saw
ISE
Microsoft.PowerShell.Management
Microsoft.PowerShell.Utility
3.I entered the command Get-Module -ListAvailable found the name of its new module ISSC.AD.Lib
4.I entered the Get-Module command again in the list and saw
ISE
Microsoft.PowerShell.Management
Microsoft.PowerShell.Utility
Connectimo
PSSharedGoods
PSWriteColor
This confused me. Why did this happen. Maybe I once configured something wrong, but I don’t remember that, I only use your modules forcibly using the Impot command, and as soon as I stop using them I unload them with the Remove command. Some kind of fantasy

**Comment by sysop200** [comment]
Modifying $ env: PSModulePath to point to my ISSC.AD.Lib module path.
The path is not standard

**Comment by PrzemyslawKlys** [comment]
Maybe ISSC .AD.lib module references some command. Hard to say.

**Comment by sysop200** [comment]
No, definitely.
This is a module written in C #
