### ISSUE TITLE
Clear passwords in memory in Set-PasswordRemotely.ps1

### ISSUE THREAD

**Issue by eworthing** [EvotecIT/PSSharedGoods#17]
After reading through this blog post https://get-powershellblog.blogspot.com/2017/06/how-safe-are-your-strings.html  I thought it might be worth mentioning that adding an end{} with the following could be more secure.

End {
$OldPasswordPlain = $Null
$NewPasswordPlain = $Null
[System.GC]::Collect()
}

**Comment by PrzemyslawKlys** [comment]
Hi,

Care for a PR? 

Przemek
