### ISSUE TITLE
Extra 't' in Get-TimeSetttings

### ISSUE THREAD

**Issue by rmbolger** [EvotecIT/PSSharedGoods#22]
Not sure if this was on purpose or not, but the English word "Settings" should only have 2 T's but the function name has 3. The file name it resides in is correct though.

https://github.com/EvotecIT/PSSharedGoods/blob/0014318fe54dee902cffbab599805025719d38d0/Public/Time/Get-TimeSettings.ps1#L66

**Comment by PrzemyslawKlys** [comment]
Not on purpose, for sure not. I'm just being sloppy. Thank you

**Comment by rmbolger** [comment]
Don't forget the reference in `FunctionsToExport` in the module manifest.

**Comment by PrzemyslawKlys** [comment]
That's one thing I don't have to worry about. In Publish folder you will notice Manage-Module.ps1 which rebuilds PSD1 on prepares a separate release for publishing. It's able to detect missing functions, build private/public entries, and do a to of other things. I've just not committed regenerated PSD1. All my projects use this. 

![image](https://user-images.githubusercontent.com/15063294/124377384-fa318600-dcab-11eb-8462-d5b965590d35.png)
![image](https://user-images.githubusercontent.com/15063294/124377390-00276700-dcac-11eb-8a99-a87b63943d79.png)
![image](https://user-images.githubusercontent.com/15063294/124377405-09b0cf00-dcac-11eb-9c20-972925fbc7ec.png)

Not everything is 100% functioning hence the module PSPublishModule is not even described anywhere - but it does work for my needs.

**Comment by rmbolger** [comment]
No worries. The only reason I noticed is because I was loading the module from a master branch clone rather than a release version.
