### ISSUE TITLE
ConvertFrom-ObjectToString: String generation enhancements

### ISSUE THREAD

**Issue by danubie** [EvotecIT/PSSharedGoods#33]
Hi,

I was starting to implement a helper to easier create "mock objects" for Pester tests from real world examples. I stumbled across "ConvertFrom-ObjectToString" which does much of the tasks I was looking for.

I would like to enhance the generated string to handle property values
- that are $null
- contain an array value
- are hashtables
in a simple fasion.

Before I create a PR I would like to understand the use case for the "$Object -is [System.Collections.IDictionary]" part.
Using my testcases, it will never get executed, because "$Object -is [Object]" already gets valid.
From my point of view, I would check for [IDictionary] before the more general "[Object]".

Can you tell me, how you use the 'IDictinionary'?

Best regards,
Wolfgang

**Comment by PrzemyslawKlys** [comment]
IDictionary is a way to cover both Hashtables and OrderedDictionary and any other Idictionary type. But just noticed order of processing was wrong.

```powershell
@{
    'Handles'     = '543'
    'Id'          = '8092'
    'ProcessName' = 'powershell'
}, @{
    'Handles'     = '543'
    'Id'          = '8092'
    'ProcessName' = 'powershell'
} | ConvertFrom-ObjectToString -IncludeProperties 'ProcessName', 'Id', 'Handles'
```

After the update - this works. It's a bit similar how @() is part of `System.Collections.IList`

**Comment by danubie** [comment]
Nicely done with checking the output via -InformationVariable. I hope I will remember it the next time I need this. Thanks for the enhanced testing.
