### ISSUE TITLE
Add automated unit tests (using Pester)

### ISSUE THREAD

**Issue by rugk** [EvotecIT/PSSharedGoods#38]
Pester seems to be a good PowerShell testing library: https://github.com/pester/Pester

IMHO unit tests add to better code quality and ease refactoring, so you should consider this, IMHO.

The current tests are rather integration tests? Or they do not really use a library: https://github.com/EvotecIT/PSSharedGoods/blob/master/Public/TestFunctionality/Test-ComputerPort.ps1
Basically it seems to be for manual testing, but Pester can e.g even mock stuff, so it may be possible to test more stuff.

Found it on https://stackoverflow.com/questions/1004424/is-there-a-unit-testing-framework-for-testing-powershell-with-powershell-scripts?noredirect=1&lq=1

**Comment by PrzemyslawKlys** [comment]
Those Tests are for testing specific services, and are not related to testing PowerShell module. 

The tests using Pester are:
- https://github.com/EvotecIT/PSSharedGoods/tree/master/Tests

And they already do some testing. Adding tests is really time consuming, but feel free to add them. Do you have anything specific that doesn't work for you, the way it used to work?

**Comment by rugk** [comment]
Ah thanks, I just thought they were not there yet. But if they are there, thanks a lot! That's good then.

As such, the issue is solved. :slightly_smiling_face:
